package chstore

import (
	"fmt"
	"log"
	"strings"
)

// FilterExpr is a single advanced filter clause: `key op value(s)`.
// `Key` may be a well-known column ("service.name", "http.method", …) or any
// custom attribute name — looked up in the attr_keys/attr_values arrays.
type FilterExpr struct {
	Key    string   `json:"k"`
	Op     string   `json:"op"`
	Values []string `json:"v"`
}

// Allowed operator set. Anything else is rejected at parse time.
var allowedOps = map[string]bool{
	"=": true, "!=": true,
	"=~": true, "!~": true, // PromQL regex matchers (v0.9.118) → CH match()
	"LIKE": true, "NOT LIKE": true,
	"IN": true, "NOT IN": true,
	">": true, ">=": true, "<": true, "<=": true,
	"EXISTS": true, "NOT EXISTS": true,
}

// wellKnownResource — RESOURCE attribute'undan dolan tipli kolonlar.
//
// wellKnown'dan AYRI olması zorunlu ve bu ayrım güvenliğin kendisi:
// wellKnown'ın çoğu (http.*, db.*, rpc.*, peer.service,
// messaging.system) SPAN attribute'undan doluyor. `resource.` dalına
// wellKnown'ı vermek `resource.http.method` sorgusunu http_method
// kolonuna düşürürdü — o kolon resource'tan DOLMUYOR, yani sessizce
// YANLIŞ sonuç.
//
// Liste ingest'ten türetildi (internal/otlp/convert.go:37-47): span
// yazılırken resource attribute'undan okunan TEK bunlar. Yeni bir
// resource→kolon eşlemesi eklenirse İKİ yer birden güncellenmeli.
var wellKnownResource = map[string]string{
	"service.name": "service_name",
	"host.name":    "host_name",
	// İki yazım da aynı kolona: ≥1.27 semconv adı ve eski adı
	// (convert.go ikisini de okuyor).
	"deployment.environment":      "deploy_env",
	"deployment.environment.name": "deploy_env",
}

// Map of well-known span attribute names to dedicated ClickHouse columns,
// so common queries skip the array lookup and stay index-friendly.
var wellKnown = map[string]string{
	"service.name":           "service_name",
	"service_name":           "service_name",
	"name":                   "name",
	"operation":              "name",
	"kind":                   "kind",
	"status_code":            "status_code",
	"status":                 "status_code",
	"host.name":              "host_name",
	"deployment.environment": "deploy_env",
	// Current semconv spelling (≥1.27) — same typed column (v0.8.379).
	"deployment.environment.name": "deploy_env",
	"http.method":                 "http_method",
	// v0.9.628 — GÜNCEL semconv yazımları (≥1.23-1.30). Ingest tarafı
	// ikisini de aynı kolona yazıyor (otlp/semconv.go spanAttrAliases);
	// filtre de ikisini de tanımak ZORUNDA, yoksa operatör modern adı
	// yazınca dizi aramasına düşer ve indeksli kolonu kaçırır.
	"http.request.method":       "http_method",
	"http.response.status_code": "http_status",
	"db.system.name":            "db_system",
	"db.query.text":             "db_statement",
	"http.route":                "http_route",
	"http.status_code":          "http_status",
	"db.system":                 "db_system",
	"db.statement":              "db_statement",
	"rpc.system":                "rpc_system",
	"rpc.method":                "rpc_method",
	"peer.service":              "peer_service",
	"messaging.system":          "msg_system",
	// v0.9.942 (UX denetimi B2) — "cluster" SPANS tarafında da bir
	// filtre anahtarı. metric_points ikizi (metricPointsWellKnown)
	// v0.9.532'den beri vardı; spans tarafında YOKTU, dolayısıyla
	// `cluster = X` çipi sessizce `attr_values[indexOf(attr_keys,
	// 'cluster')]` dizi aramasına düşüyordu — yani k8s.cluster.name /
	// openshift.cluster.name basan (yani ÇOĞU) kurulumda HİÇBİR satır
	// eşleşmiyordu. Boş sonuç değil, YANLIŞ KAPSAM: /endpoints'te
	// cluster seçip Explore'a pivotlayan operatör tüm cluster'ları
	// görüyordu.
	//
	// clusterDeriveExpr, o dizi aramasının ÜST KÜMESİ (6 permütasyonun
	// biri tam olarak eski davranış), yani mevcut hiçbir sorgu sonuç
	// KAYBETMEZ. Terfi edilmiş `cluster` kolonu burada BİLİNÇLİ
	// kullanılmıyor: FilterExpr.SQL() saf ve Store'un hasClusterCol
	// probunu göremez; kolonu olmayan harici Distributed kurulumda
	// kolon adı code 47 verirdi (v0.8.162). Derive her iki şekilde de
	// doğru; maliyeti yalnız operatör bir cluster SEÇTİĞİNDE ödenir.
	"cluster":     clusterDeriveExpr,
	"duration_ms": "(duration / 1e6)",
	// v0.5.271 — added for DQL cross-signal join. The
	// FilterExpr{Key:"trace.id", Op:"IN", Values:[ids]} shape
	// generated by the join executor needs the dotted form to
	// resolve to the dedicated trace_id column.
	"trace.id": "trace_id",
	"traceId":  "trace_id",
	"trace_id": "trace_id",
	"span.id":  "span_id",
	"span_id":  "span_id",
}

// SQL builds the WHERE fragment + arg list for this filter, or returns
// (empty, nil, error) if the expression is malformed.
//
// For unknown attribute keys, the lookup expression `attr_values[indexOf(attr_keys, ?)]`
// pushes the key as a parameter. For numeric ops we cast to Float64 so that
// even string-stored attributes compare correctly when they parse.
func (f FilterExpr) SQL() (string, []any, error) {
	return f.sql("", wellKnown, wellKnownResource, promotedCols(), AttrIndexAvailable())
}

// SQLWithPromoted — v0.10.339: terfi haritası ÇAĞIRANDAN. nil = dizi yolu
// (TraceFilter.NoPromoted; promoted_attr.go §v0.10.339 uyuşmazlık düşüşü).
func (f FilterExpr) SQLWithPromoted(promoted map[string]string) (string, []any, error) {
	return f.sql("", wellKnown, wellKnownResource, promoted, AttrIndexAvailable())
}

// SQLForMetricPoints resolves against metric_points' column set
// (v0.8.381): only service/host typed columns exist there, so every
// other wellKnown key falls to the attr/res array lookups instead of
// referencing a spans-only column ClickHouse would reject.
func (f FilterExpr) SQLForMetricPoints() (string, []any, error) {
	// promoted=nil: terfi kolonları SPANS'a özgü. v0.9.619'un dersi —
	// paylaşılan üretecin içine harita GÖMÜLMEZ, parametre olarak gelir;
	// aksi halde metric_points'te var olmayan bir kolona referans üretir.
	return f.sql("", metricPointsWellKnown, nil, nil, false) // v0.10.300 — metric_points'te kvh kolonu YOK
}

// SQLAliased is the alias-qualified twin of SQL: every column reference is
// prefixed with `<alias>.` so the fragment is safe to use inside a self-join
// over `spans AS <alias>` (relations.go, v0.8.x). With an empty alias it is
// byte-identical to SQL() — the existing flat-filter callers are unchanged.
//
// Only the alias is concatenated into the SQL text; it is validated by the
// caller (relations.go uses the fixed literals "c" / "p"), never threaded
// from user input. Keys and values still flow exclusively as `?` params.
func (f FilterExpr) SQLAliased(alias string) (string, []any, error) {
	return f.sql(alias, wellKnown, wellKnownResource, promotedCols(), AttrIndexAvailable())
}

// qualCol prefixes a well-known column expression (which may itself be a
// compound expression like "(duration / 1e6)") with the join alias. An empty
// alias is a no-op so SQL() stays byte-identical to its pre-alias form.
func qualCol(alias, col string) string {
	if alias == "" {
		return col
	}
	// Compound well-known expr — only `(duration / 1e6)` today. Qualify the
	// inner column rather than the whole parenthesised expression.
	if strings.HasPrefix(col, "(") {
		return strings.Replace(col, "duration", alias+".duration", 1)
	}
	return alias + "." + col
}

// qualArr prefixes the array-lookup columns (attr/res keys+values) with the
// join alias. arrCol is the bare expression, e.g.
// "attr_values[indexOf(attr_keys, ?)]" or "has(res_keys, ?)".
func qualArr(alias, expr string) string {
	if alias == "" {
		return expr
	}
	r := strings.NewReplacer(
		"attr_values", alias+".attr_values",
		"attr_keys", alias+".attr_keys",
		"attr_kvh", alias+".attr_kvh", // v0.10.300
		"res_values", alias+".res_values",
		"res_keys", alias+".res_keys",
		"res_kvh", alias+".res_kvh",
	)
	return r.Replace(expr)
}

// resourceWellKnown: RESOURCE attribute'undan dolan tipli kolonlar.
// Tabloya ÖZEL ve wellKnown'dan ayrı olması şart — gerekçe
// wellKnownResource tanımında. nil geçmek "bu tabloda resource→kolon
// eşlemesi yok" demek ve davranışı dizi aramasında bırakır.
// promoted: operatör tarafından terfi ettirilmiş ÖZEL attribute anahtarları
// (traceAttrMaterialized). nil geçmek "bu tabloda terfi kolonu yok" demek —
// metric_points yolu böyle geçiyor.
//
// v0.9.622 — filtre yolu bu haritaya BAKMIYORDU ve bu, terfi kolonlarının
// tüm noktasını kaçırıyordu: /traces gösterim kolonları (traceExtrasProjection)
// ve kırılımlar (businessDimExpr) haritayı kullanıyordu ama FİLTRE — yani
// pahalı olan taraf — koşulsuz dizi aramasına düşüyordu.
//
// Operator-reported sonuç: channel_code filtresi 6 saatlik pencerede iki
// büyük Array(String) kolonunu her span için açıyor, granül eleme yok,
// 26 sn'de max_execution_time'a takılıyor.
//
// Ölçüldü (CH 24.8, 10M satır, 3 koşu medyanı):
//
//	dizi açma            3.90 GiB   362 ms
//	terfi kolonu         1.98 GiB   204 ms
//	kolon + skip index    261 MiB    81 ms
//
// kvh (v0.10.300, trace arama Dilim 1b) — attribute hash indeksi hazır mı
// (attr_index.go). Dizi yoluna düşen `=` / `IN` yüklemleri, ÖNÜNE bloom'un
// kullanabildiği `has(attr_kvh, cityHash64(k<0x1F>v))` alır; kesin dizi
// eşitliği KALIR (bloom yanlış-pozitifi eler — doğruluk indekse asılı
// değil). Terfi kolonu / bilinen kolon / negasyon / regex / aralık aynen.
func (f FilterExpr) sql(alias string, wellKnown, resourceWellKnown, promoted map[string]string, kvh bool) (string, []any, error) {
	op := strings.ToUpper(strings.TrimSpace(f.Op))
	if op == "" {
		op = "="
	}
	if !allowedOps[op] {
		return "", nil, fmt.Errorf("invalid operator %q", op)
	}
	if f.Key == "" {
		return "", nil, fmt.Errorf("missing key")
	}

	// Resolve the LHS expression. Tempo-style prefixes pick the array:
	//   resource.X  →  res_values[indexOf(res_keys, 'X')]
	//   span.X      →  attr_values[indexOf(attr_keys, 'X')]
	//   X           →  well-known dedicated column if any, else span attr
	var lhs string
	var args []any
	// kvhCol / arrKey — dizi yoluna düşüldüyse bloom kolonu ve ham anahtar
	// (v0.10.300); terfi/bilinen kolonda boş kalır.
	var kvhCol, arrKey string
	switch {
	case strings.HasPrefix(f.Key, "resource."):
		name := strings.TrimPrefix(f.Key, "resource.")
		// v0.9.619 — resource dalı da TİPLİ KOLONA düşebilir.
		//
		// Öncesi koşulsuz dizi aramasıydı: `resource.service.name = X`
		// spans'in birincil anahtar budamasını (ORDER BY service_name,
		// time) TAMAMEN kaybediyordu — aynı soru `service.name = X`
		// yazılınca indeksli kolona düşerken.
		//
		// Üstelik UI operatörü oraya İTİYOR: FilterBuilder'ın statik
		// öneri listesi `resource.service.name` / `resource.host.name` /
		// `resource.deployment.environment` içeriyor ve canlı öneriler
		// de resource kapsamındaki anahtarı `resource.` önekiyle
		// sunuyor. Yani önerilen yol, yavaş yoldu.
		// v0.10.127 — resource kapsamlı TERFİ kolonu önce (k8s_pod vb.);
		// probe bu anahtarları `resource.` önekli yazımla da kaydeder.
		if col, ok := promoted[f.Key]; ok {
			lhs = qualCol(alias, col)
		} else if col, ok := resourceWellKnown[name]; ok {
			lhs = qualCol(alias, col)
		} else {
			lhs = qualArr(alias, "res_values[indexOf(res_keys, ?)]")
			args = append(args, name)
			kvhCol, arrKey = qualArr(alias, "res_kvh"), name
		}
	case strings.HasPrefix(f.Key, "span."):
		name := strings.TrimPrefix(f.Key, "span.")
		// v0.9.622 — çözümleme sırası traceExtrasProjection /
		// businessDimExpr ile AYNI: terfi kolonu → well-known → dizi.
		// Üç yerde üç farklı sıra olsaydı aynı anahtar aynı sayfada
		// farklı kolonlardan okunurdu.
		if col, ok := promoted[name]; ok {
			lhs = qualCol(alias, col)
		} else if col, ok := wellKnown[name]; ok {
			// Allow span.<known> to fall back to the dedicated column for indexing
			lhs = qualCol(alias, col)
		} else {
			lhs = qualArr(alias, "attr_values[indexOf(attr_keys, ?)]")
			args = append(args, name)
			kvhCol, arrKey = qualArr(alias, "attr_kvh"), name
		}
	default:
		if col, ok := promoted[f.Key]; ok {
			lhs = qualCol(alias, col)
		} else if col, ok := wellKnown[f.Key]; ok {
			lhs = qualCol(alias, col)
		} else {
			lhs = qualArr(alias, "attr_values[indexOf(attr_keys, ?)]")
			args = append(args, f.Key)
			kvhCol, arrKey = qualArr(alias, "attr_kvh"), f.Key
		}
	}

	// Numeric ops get a Float64 cast — `attr_values` is String, so this
	// turns "200" into 200.0 for comparison without breaking text columns.
	if !kvh {
		kvhCol = ""
	}
	numericOp := op == ">" || op == ">=" || op == "<" || op == "<="

	switch op {
	case "EXISTS", "NOT EXISTS":
		neg := op == "NOT EXISTS"
		// v0.9.622 — EXISTS terfi kolonuna BİLİNÇLİ olarak yönlenmiyor.
		// `has(attr_keys,'k')` ile `col != ''` eşdeğer DEĞİL: anahtar
		// BOŞ DEĞERLE varsa ilki true, ikincisi false döner. Kazanç da
		// küçük — EXISTS zaten yalnız attr_keys'i okuyor, değer
		// karşılaştırmaları gibi iki diziyi birden açmıyor.
		//
		// Pick the right array (or use the dedicated column if well-known).
		var hasExpr string
		var hArgs []any
		switch {
		case strings.HasPrefix(f.Key, "resource."):
			name := strings.TrimPrefix(f.Key, "resource.")
			hasExpr = qualArr(alias, "has(res_keys, ?)")
			hArgs = []any{name}
		case strings.HasPrefix(f.Key, "span."):
			name := strings.TrimPrefix(f.Key, "span.")
			if _, ok := wellKnown[name]; ok {
				hasExpr = "(" + qualCol(alias, wellKnown[name]) + " != '')"
			} else {
				hasExpr = qualArr(alias, "has(attr_keys, ?)")
				hArgs = []any{name}
			}
		default:
			if _, ok := wellKnown[f.Key]; ok {
				hasExpr = "(" + qualCol(alias, wellKnown[f.Key]) + " != '')"
			} else {
				hasExpr = qualArr(alias, "has(attr_keys, ?)")
				hArgs = []any{f.Key}
			}
		}
		if neg {
			hasExpr = "NOT " + hasExpr
		}
		return hasExpr, hArgs, nil

	case "IN", "NOT IN":
		if len(f.Values) == 0 {
			return "", nil, fmt.Errorf("op %s needs at least one value", op)
		}
		placeholders := strings.TrimRight(strings.Repeat("?,", len(f.Values)), ",")
		if op == "IN" && kvhCol != "" {
			// v0.10.300 — bloom: hasAny(kvh, [hash(k,v1), hash(k,v2), …]) AND kesin IN.
			hashes := make([]string, len(f.Values))
			pre := make([]any, 0, 2*len(f.Values))
			for i, v := range f.Values {
				hashes[i] = AttrKVHashSQL
				pre = append(pre, arrKey, v)
			}
			all := append(pre, args...)
			for _, v := range f.Values {
				all = append(all, v)
			}
			attrIndexUsed.Add(1)
			return "(hasAny(" + kvhCol + ", [" + strings.Join(hashes, ", ") + "]) AND " +
				lhs + " IN (" + placeholders + "))", all, nil
		}
		for _, v := range f.Values {
			args = append(args, v)
		}
		return lhs + " " + op + " (" + placeholders + ")", args, nil

	case "LIKE", "NOT LIKE":
		if len(f.Values) != 1 {
			return "", nil, fmt.Errorf("op %s needs exactly one value", op)
		}
		args = append(args, "%"+f.Values[0]+"%")
		return lhs + " " + op + " ?", args, nil

	case "=~", "!~":
		// PromQL regex matchers → ClickHouse match() (both RE2). PromQL fully
		// anchors the pattern (must match the WHOLE label value); match() does
		// not, so wrap in ^(?:…)$. lhs coerced to String for attr/column parity.
		if len(f.Values) != 1 {
			return "", nil, fmt.Errorf("op %s needs exactly one value", op)
		}
		args = append(args, "^(?:"+f.Values[0]+")$")
		m := "match(toString(" + lhs + "), ?)"
		if op == "!~" {
			return "NOT (" + m + ")", args, nil
		}
		return m, args, nil

	default: // =, !=, comparison ops
		if len(f.Values) != 1 {
			return "", nil, fmt.Errorf("op %s needs exactly one value", op)
		}
		if numericOp {
			// Cast to Float64. accurateCastOrNull is type-tolerant and handles
			// both String (attribute lookups) and numeric (well-known) columns.
			args = append(args, f.Values[0])
			return "accurateCastOrNull(" + lhs + ", 'Float64') " + op +
				" accurateCastOrNull(?, 'Float64')", args, nil
		}
		if op == "=" && kvhCol != "" {
			// v0.10.300 — bloom önce (granül budar), kesin eşitlik sonra
			// (yanlış-pozitif eler). Bağlama sırası: hash(k, v), dizi anahtarı, v.
			all := append([]any{arrKey, f.Values[0]}, args...)
			all = append(all, f.Values[0])
			attrIndexUsed.Add(1)
			return "(has(" + kvhCol + ", " + AttrKVHashSQL + ") AND " + lhs + " = ?)", all, nil
		}
		args = append(args, f.Values[0])
		return lhs + " " + op + " ?", args, nil
	}
}

// ApplyFilters appends each filter as a separate WHERE conjunct, skipping any
// that fail to compile.
//
// v0.9.269 — the skip is now LOGGED. It used to be silent, justified by
// "UI validates first", and that assumption was false: the DB drill modal
// sent `{key, op, value}` while this struct binds `{k, op, v}` by JSON tag,
// so Key arrived empty, SQL() returned "missing key", and every filter was
// dropped here without a trace. The chart then rendered UNFILTERED under a
// modal that displayed the filter chip. A dropped filter does not produce an
// empty result an operator would question — it produces a WIDER one that
// looks perfectly plausible, which is the worst way for this to fail.
//
// Skipping (rather than erroring) is kept deliberately: a hard failure here
// would take down every caller for one malformed clause. But it must not be
// invisible.
func ApplyFilters(wc *whereClause, filters []FilterExpr) {
	ApplyFiltersWith(wc, filters, promotedCols())
}

// ApplyFiltersWith — v0.10.339: terfi haritası parametre (nil = dizi yolu).
func ApplyFiltersWith(wc *whereClause, filters []FilterExpr, promoted map[string]string) {
	for _, f := range filters {
		sql, args, err := f.SQLWithPromoted(promoted)
		if err != nil || sql == "" {
			log.Printf("[filter] DROPPED span filter key=%q op=%q values=%d: %v — "+
				"result is UNFILTERED for this clause", f.Key, f.Op, len(f.Values), err)
			continue
		}
		wc.add(sql, args...)
	}
}

// metricPointsWellKnown resolves filter keys against metric_points'
// ACTUAL columns (v0.8.381, audit-found: picking deployment.environment
// in the Explore metric filter referenced the spans-only deploy_env
// column and 500'd). Only service/host typed columns exist there; the
// env keys map straight to the resource-array lookup (either semconv
// spelling matches, mirroring what deploy_env gives spans), and every
// other key falls through to the generic datapoint-attr lookup.
var metricPointsWellKnown = map[string]string{
	"service.name": "service_name", "service_name": "service_name", "service": "service_name",
	"host.name": "host_name", "host_name": "host_name",
	"deployment.environment":      metricEnvExpr,
	"deployment.environment.name": metricEnvExpr,
	// v0.9.532 — operatör raporu: Runtime—JVM pod grafiklerinde hangi
	// pod'un hangi cluster'da olduğu belli değildi. "cluster" anahtarı
	// spans tarafındaki clusterDeriveExpr'in (repo.go) metric_points
	// ikizine çözümlenir. TEK anahtar (k8s.cluster.name) YETMEZ —
	// v0.9.52 dersi: yalnız openshift.cluster.name basan cluster var;
	// coalesce atlanırsa o cluster'ın pod'ları sessizce öneksiz kalır.
	"cluster": metricClusterExpr,
}

// IsMetricPointsWellKnownKey — v0.10.944: anahtar metric_points'in kolon-
// destekli iyi bilinen anahtarlarından mı (service.name, host.name,
// deployment.environment[.name], cluster …). mcptools query_metric CH yolu
// bu anahtarları etiket keşfi listesinde (MetricAttrKeys yalnız veri noktası
// öznitelikleri) göremez; harita KOPYALANMAZ — iki kopya zamanla ayrışırdı.
func IsMetricPointsWellKnownKey(k string) bool {
	_, ok := metricPointsWellKnown[k]
	return ok
}

const metricEnvExpr = "coalesce(nullIf(res_values[indexOf(res_keys, 'deployment.environment.name')], ''), " +
	"res_values[indexOf(res_keys, 'deployment.environment')])"

// metricClusterExpr — clusterDeriveExpr'in (repo.go) metric_points
// kopyası: aynı 6 permütasyon, aynı sıra (resource önce). Anahtar seti
// filterexpr_test'te clusterDeriveExpr'e pinli — ayrışırlarsa spans ve
// metrics yüzeyleri aynı pod'u farklı cluster'da gösterir.
const metricClusterExpr = `coalesce(
	nullIf(res_values[indexOf(res_keys, 'k8s.cluster.name')], ''),
	nullIf(res_values[indexOf(res_keys, 'openshift.cluster.name')], ''),
	nullIf(res_values[indexOf(res_keys, 'cluster')], ''),
	nullIf(attr_values[indexOf(attr_keys, 'k8s.cluster.name')], ''),
	nullIf(attr_values[indexOf(attr_keys, 'openshift.cluster.name')], ''),
	nullIf(attr_values[indexOf(attr_keys, 'cluster')], ''),
	'')`

// groupKeyExprMetric is groupKeyExpr for a metric_points GROUP BY (v0.9.126,
// review fix). The generic groupKeyExpr resolves against the SPANS wellKnown
// map, whose columns (http_method, db_system, kind, status_code, name, …) do
// NOT exist on metric_points — so a datapoint attr like http.method reached the
// GROUP BY as a nonexistent column → ClickHouse code 47 → 500. That is the
// v0.8.381 filter-path incident on the GROUP BY path, and PromQL without()
// makes it unavoidable (it auto-discovers + groups by every attr key). Here
// only service/host/deployment.environment resolve to real columns; everything
// else is a datapoint-attr array lookup.
func groupKeyExprMetric(key string) (string, []any) {
	if strings.HasPrefix(key, "resource.") {
		return "toString(res_values[indexOf(res_keys, ?)])", []any{strings.TrimPrefix(key, "resource.")}
	}
	if col, ok := metricPointsWellKnown[key]; ok {
		return "toString(" + col + ")", nil
	}
	return "toString(attr_values[indexOf(attr_keys, ?)])", []any{key}
}

// ApplyMetricFilters is ApplyFilters for metric_points reads
// (v0.8.381): identical semantics, metric-aware column resolution.
func ApplyMetricFilters(wc *whereClause, filters []FilterExpr) {
	for _, f := range filters {
		sql, args, err := f.SQLForMetricPoints()
		if err != nil || sql == "" {
			// See ApplyFilters above — this is the path the DB drill modal
			// fell down, silently, for every filter it ever sent.
			log.Printf("[filter] DROPPED metric filter key=%q op=%q values=%d: %v — "+
				"result is UNFILTERED for this clause", f.Key, f.Op, len(f.Values), err)
			continue
		}
		wc.add(sql, args...)
	}
}

// FilterGroup is a grouped boolean combination of FilterExpr leaves and
// (one level of) nested groups, joined by a single AND/OR operator. It is
// the additive, default-off upgrade over the flat conjunction-only
// `[]FilterExpr` path: an operator can finally express
// `(http.status >= 500 OR db.system = oracle) AND env = prod`.
//
// Depth cap: v1 supports exactly ONE level of nested groups. The top-level
// group may carry Groups; nested groups carry only Filters (deeper Groups
// are ignored by BuildFilterGroupSQL). One level buys ~95% of real queries
// per the trace-query-explore spec; arbitrary nesting is a bigger UI + URL
// codec lift deferred past v1.
//
// BACK-COMPAT CONTRACT (pinned by filtergroup_test.go): a flat-AND group —
// `FilterGroup{Join:"AND", Filters:<legacy []FilterExpr>}` with no Groups —
// emits byte-identical SQL + args to the legacy ApplyFilters path, so saved
// views / shared URLs / DQL / facets are untouched. The flat-AND case is
// routed straight through ApplyFilters precisely so it cannot drift.
type FilterGroup struct {
	Join    string        `json:"join"` // "AND" | "OR" (default AND)
	Filters []FilterExpr  `json:"filters"`
	Groups  []FilterGroup `json:"groups,omitempty"`
}

// isFlatAnd reports whether the group is equivalent to the legacy flat
// conjunction-only path: AND-joined leaves, no nested groups. Used both by
// ApplyFilterGroup (to take the byte-identical fast path) and by the
// repo-layer MV gate (an OR / nested group disqualifies the
// trace_summary_5m fast-path exactly like Search / custom-attr does today).
func (g FilterGroup) isFlatAnd() bool {
	if len(g.Groups) > 0 {
		return false
	}
	return joinOp(g.Join) == "AND"
}

// IsFlatAnd is the exported guard the repo MV gate calls on an optional
// *FilterGroup: a nil root or a flat-AND root keeps the MV fast-path; any
// OR / nested group falls to the raw-spans GROUP-BY path (same cost class
// as free-text Search today).
func (g *FilterGroup) IsFlatAnd() bool {
	if g == nil {
		return true
	}
	return g.isFlatAnd()
}

// hasPredicate reports whether the group would contribute ANY compilable
// WHERE term. nil-safe so the repo MV gate can call it on an optional
// *FilterGroup: a nil or empty root contributes nothing (MV fast-path
// stays eligible), any compilable leaf — flat-AND or OR — disqualifies the
// MV exactly like a legacy non-empty Filters slice does today.
func (g *FilterGroup) hasPredicate() bool {
	if g == nil {
		return false
	}
	sql, _ := BuildFilterGroupSQL(*g)
	return sql != ""
}

// joinOp normalises the join operator to "AND" or "OR"; anything unknown /
// empty defaults to "AND" (the safe, legacy-equivalent operator).
func joinOp(j string) string {
	if strings.EqualFold(strings.TrimSpace(j), "OR") {
		return "OR"
	}
	return "AND"
}

// buildGroupFragment renders a group to a single parenthesised SQL fragment
// + ordered args, reusing FilterExpr.SQL() per leaf. Malformed / empty
// leaves are silently skipped (mirrors ApplyFilters' contract). nested is
// true when rendering a child group (caps the depth at one level — a
// nested group's own Groups are ignored).
//
// Returns ("", nil) when the group yields no compilable terms, so the
// caller can omit it entirely.
func buildGroupFragment(g FilterGroup, nested bool) (string, []any) {
	return buildGroupFragmentWith(g, nested, promotedCols())
}

// buildGroupFragmentWith — v0.10.339: terfi haritası parametre (nil = dizi yolu).
func buildGroupFragmentWith(g FilterGroup, nested bool, promoted map[string]string) (string, []any) {
	op := joinOp(g.Join)
	var parts []string
	var args []any
	for _, f := range g.Filters {
		sql, fargs, err := f.SQLWithPromoted(promoted)
		if err != nil || sql == "" {
			continue // silently skip — UI validates first
		}
		parts = append(parts, sql)
		args = append(args, fargs...)
	}
	if !nested {
		for _, sub := range g.Groups {
			// Depth cap: render child groups as leaf fragments (their own
			// Groups are ignored — see the FilterGroup depth-cap doc).
			frag, fargs := buildGroupFragment(sub, true)
			if frag == "" {
				continue
			}
			parts = append(parts, frag)
			args = append(args, fargs...)
		}
	}
	if len(parts) == 0 {
		return "", nil
	}
	if len(parts) == 1 {
		// A single term needs no wrapping parens when it's already a
		// self-contained fragment; but a nested child is always wrapped so
		// the parent's join can't bind across it. Top-level single term
		// returns bare (matches the flat path's per-conjunct add).
		if nested {
			return "(" + parts[0] + ")", args
		}
		return parts[0], args
	}
	return "(" + strings.Join(parts, " "+op+" ") + ")", args
}

// BuildFilterGroupSQL renders a FilterGroup to a single WHERE fragment +
// ordered args, ready to AND onto the rest of a query's predicates. Returns
// ("", nil) for a group with no compilable terms.
//
// For a flat-AND group it produces the same per-leaf SQL the legacy path
// produces, joined by " AND " (no outer parens at the top level when there's
// a single combined fragment) — but callers that need byte-identical
// behaviour with ApplyFilters should use ApplyFilterGroup, which routes the
// flat-AND case straight through ApplyFilters.
func BuildFilterGroupSQL(g FilterGroup) (string, []any) {
	return buildGroupFragment(g, false)
}

// ApplyFilterGroup appends a FilterGroup's predicates onto a whereClause.
//
//   - Flat-AND (no OR, no nested groups): delegated VERBATIM to ApplyFilters
//     so the emitted conds + args are byte-identical to the legacy
//     `[]FilterExpr` path — each leaf is a separate ` AND `-joined conjunct.
//     This is the zero-risk back-compat path saved views ride on.
//   - Anything with OR or a nested group: rendered to a single parenthesised
//     fragment via BuildFilterGroupSQL and added as ONE conjunct, so the
//     group's internal boolean structure is preserved against the
//     surrounding (always-AND) time / service / error predicates.
func ApplyFilterGroup(wc *whereClause, g FilterGroup) {
	ApplyFilterGroupWith(wc, g, promotedCols())
}

// ApplyFilterGroupWith — v0.10.339: terfi haritası parametre (nil = dizi yolu).
func ApplyFilterGroupWith(wc *whereClause, g FilterGroup, promoted map[string]string) {
	if g.isFlatAnd() {
		ApplyFiltersWith(wc, g.Filters, promoted)
		return
	}
	sql, args := buildGroupFragmentWith(g, false, promoted)
	if sql == "" {
		return
	}
	wc.add(sql, args...)
}

// leaves — v0.10.339: kök + bir seviye alt grupların yaprak filtreleri
// (buildGroupFragment'ın gezdiği derinlikle aynı).
func (g FilterGroup) leaves() []FilterExpr {
	out := append([]FilterExpr(nil), g.Filters...)
	for _, sub := range g.Groups {
		out = append(out, sub.Filters...)
	}
	return out
}

// ── v0.10.118 — SINIRDA DOĞRULAMA ──────────────────────────────────────
//
// Ölçülen olay (perf keşfi 2026-08-28): `filters=[{"k":…,"op":"contains"}]`
// → op allowedOps'ta yok → ApplyFilters yan tümceyi (v0.9.269 kararıyla)
// LOGLAYIP ATLADI → MV yolu yan tümcenin VARLIĞI yüzünden diskalifiye,
// ham `GROUP BY trace_id` 24h penceresinin TAMAMINI taradı (1.57 M satır,
// 6.2 s) ve 51 FİLTRESİZ satır döndü. v0.9.269'un kendi yorumu bunun
// "en kötü hata modu" olduğunu yazıyor; loglamak görünür kıldı ama
// sonucu değiştirmedi. Bundan sonra derlenemeyecek bir yan tümce API
// SINIRINDA reddedilir (400); ApplyFilters'ın atlaması yalnız son çare.

// Validate — yan tümce derlenebilir mi: op allowedOps'ta (boş = "="),
// anahtar dolu. SQL üretmez, saf; parse anında çağrılır.
func (f FilterExpr) Validate() error {
	op := strings.ToUpper(strings.TrimSpace(f.Op))
	if op == "" {
		op = "="
	}
	if !allowedOps[op] {
		return fmt.Errorf("invalid operator %q for key %q (allowed: =, !=, =~, !~, LIKE, NOT LIKE, IN, NOT IN, >, >=, <, <=, EXISTS, NOT EXISTS)", f.Op, f.Key)
	}
	if strings.TrimSpace(f.Key) == "" {
		return fmt.Errorf("filter with operator %q has no key", f.Op)
	}
	return nil
}

// ValidateFilters — listedeki İLK derlenemeyen yan tümcenin hatası.
func ValidateFilters(fs []FilterExpr) error {
	for i, f := range fs {
		if err := f.Validate(); err != nil {
			return fmt.Errorf("filters[%d]: %w", i, err)
		}
	}
	return nil
}

// Validate — grubun yaprakları + bir seviye alt grup (buildGroupFragment
// derinlik tavanıyla aynı); nil grup geçerli.
func (g *FilterGroup) Validate() error {
	if g == nil {
		return nil
	}
	if err := ValidateFilters(g.Filters); err != nil {
		return fmt.Errorf("filterGroup: %w", err)
	}
	for i, sub := range g.Groups {
		if err := ValidateFilters(sub.Filters); err != nil {
			return fmt.Errorf("filterGroup.groups[%d]: %w", i, err)
		}
	}
	return nil
}
